-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 17:45:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_Aqua_quality
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Aqua_quality
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Aqua_quality` ;
USE `db_Aqua_quality` ;

-- -----------------------------------------------------
-- Table `db_Aqua_quality`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Aqua_quality`.`tb_usuario` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_Aqua_quality`.`tb_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Aqua_quality`.`tb_temas` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `categoriaPostagem` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_Aqua_quality`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_Aqua_quality`.`tb_postagens` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(1000) NOT NULL,
  `texto` VARCHAR(1000) NOT NULL,
  `dataPostagem` DATETIME NOT NULL,
  `midia` VARCHAR(1000) NULL DEFAULT NULL,
  `usuario_id` BIGINT NULL DEFAULT NULL,
  `temas_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`usuario_id` ASC) VISIBLE,
  INDEX (`temas_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_Aqua_quality`.`tb_usuario` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`temas_id`)
    REFERENCES `db_Aqua_quality`.`tb_temas` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
